### ISSUE TITLE
Introduce track points query object

### ISSUE THREAD

**Issue by skyksandr** [skyderby/skyderby#71]
**Problem**

Now track points queried from 17 places, all queries shares similar concept.

**Solution**

Create abstraction for this case and use one object that represents query to db for points.

Usage:
```
TrackPointsQuery.new(track, opts = {})
```

```
opts:
 - freq_1Hz: true/false (default: false), if true then  reorder('round(gps_time_in_seconds)’) and add 'DISTINCT ON (round(gps_time_in_seconds))' to the first field.
 - trimmed: true/false (default: false), if true - add trimmed scope with trim_from.
 - trim_from: number (default: 0)
 - only: [] - ability to specify columns to select
 - except: [] - ability to exclude columns from query
```

Columns:
```
 - gps_time = to_timestamp(gps_time_in_seconds) AT TIME ZONE 'UTC'
 - fl_time = gps_time_in_seconds - #{start_time_in_seconds}

 - altitude = #{@track.point_altitude_field}


 - latitude
 - longitude
 - h_speed
 - v_speed
 - distance
 - 'CASE WHEN v_speed = 0 THEN h_speed / 0.1
                  ELSE h_speed / ABS(v_speed)
            END AS glide_ratio'

 - (EXPENSIVE IN QUERY) time_diff
```

—.where("#{track.point_altitude_field} > 1200")
